"""Add created_at to user

Revision ID: 5d88c6b103a7
Revises: f4026b359d0e
Create Date: 2025-06-04 18:09:12.446689

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d88c6b103a7'
down_revision: Union[str, None] = 'f4026b359d0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Check if column exists before adding it
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    
    # Get existing columns
    user_columns = [col['name'] for col in inspector.get_columns('users')]
    
    # Only add column if it doesn't exist
    if 'created_at' not in user_columns:
        op.add_column('users', sa.Column('created_at', sa.DateTime(), nullable=True))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'created_at')
    # ### end Alembic commands ###
