"""add_applications_table_for_oauth2

Revision ID: 6d9b3e1ee793
Revises: a1b2c3d4e5f6
Create Date: 2025-12-06 20:40:22.683075

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d9b3e1ee793'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Check if table exists before creating it
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    tables = inspector.get_table_names()
    
    if 'applications' not in tables:
        op.create_table('applications',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('client_id', sa.String(), nullable=False),
            sa.Column('client_secret_hash', sa.String(), nullable=False),
            sa.Column('name', sa.String(), nullable=False),
            sa.Column('description', sa.String(), nullable=True),
            sa.Column('scopes', sa.JSON(), nullable=True),
            sa.Column('is_active', sa.Boolean(), nullable=True),
            sa.Column('created_at', sa.DateTime(), nullable=True),
            sa.Column('last_used_at', sa.DateTime(), nullable=True),
            sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_applications_client_id'), 'applications', ['client_id'], unique=True)
        op.create_index(op.f('ix_applications_id'), 'applications', ['id'], unique=False)
    else:
        # Table exists, verify indexes exist
        existing_indexes = [idx['name'] for idx in inspector.get_indexes('applications')]
        if 'ix_applications_client_id' not in existing_indexes:
            try:
                op.create_index(op.f('ix_applications_client_id'), 'applications', ['client_id'], unique=True)
            except Exception:
                pass
        if 'ix_applications_id' not in existing_indexes:
            try:
                op.create_index(op.f('ix_applications_id'), 'applications', ['id'], unique=False)
            except Exception:
                pass


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_applications_id'), table_name='applications')
    op.drop_index(op.f('ix_applications_client_id'), table_name='applications')
    op.drop_table('applications')
    # ### end Alembic commands ###
