"""Add user birthdate and user_type

Revision ID: c497361d4ea0
Revises: 
Create Date: 2025-05-31 19:06:35.434257

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c497361d4ea0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Check if users table exists, if not create it
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    tables = inspector.get_table_names()
    
    if 'users' not in tables:
        # Create users table with all required columns
        op.create_table('users',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('hashed_password', sa.String(), nullable=True),
            sa.Column('first_name', sa.String(), nullable=True),
            sa.Column('last_name', sa.String(), nullable=True),
            sa.Column('phone', sa.String(), nullable=True),
            sa.Column('whatsapp_phone', sa.String(), nullable=True),
            sa.Column('email', sa.String(), nullable=True),
            sa.Column('birthdate', sa.Date(), nullable=True),
            sa.Column('user_type', sa.String(), nullable=False, server_default='client'),
            sa.Column('registration_complete', sa.Boolean(), nullable=True, server_default='true'),
            sa.Column('created_at', sa.DateTime(), nullable=True),
            sa.Column('password_requires_update', sa.Boolean(), nullable=True, server_default='false'),
            sa.Column('password_last_updated', sa.DateTime(), nullable=True),
            sa.Column('is_suspended', sa.Boolean(), nullable=True, server_default='false'),
            sa.Column('suspended_at', sa.DateTime(), nullable=True),
            sa.Column('suspended_reason', sa.String(), nullable=True),
            sa.Column('is_blocked', sa.Boolean(), nullable=True, server_default='false'),
            sa.Column('blocked_at', sa.DateTime(), nullable=True),
            sa.Column('blocked_reason', sa.String(), nullable=True),
            sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
        op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
        op.create_index(op.f('ix_users_whatsapp_phone'), 'users', ['whatsapp_phone'], unique=True)
        op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    else:
        # Table exists, just add the columns if they don't exist
        user_columns = [col['name'] for col in inspector.get_columns('users')]
        if 'birthdate' not in user_columns:
            op.add_column('users', sa.Column('birthdate', sa.Date(), nullable=True))
        if 'user_type' not in user_columns:
            op.add_column('users', sa.Column('user_type', sa.String(), nullable=True))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'user_type')
    op.drop_column('users', 'birthdate')
    # ### end Alembic commands ###
