"""add_single_access_tokens_and_user_fields

Revision ID: d0bfed9cad13
Revises: 6d9b3e1ee793
Create Date: 2025-12-07 10:55:31.828410

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0bfed9cad13'
down_revision: Union[str, None] = '6d9b3e1ee793'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create single_access_tokens table (if not exists)
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    tables = inspector.get_table_names()
    
    if 'single_access_tokens' not in tables:
        op.create_table('single_access_tokens',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('user_id', sa.Integer(), nullable=False),
            sa.Column('token', sa.String(), nullable=False),
            sa.Column('redirect_url', sa.String(), nullable=True),
            sa.Column('created_at', sa.DateTime(), nullable=True),
            sa.Column('expires_at', sa.DateTime(), nullable=False),
            sa.Column('used', sa.Boolean(), nullable=True),
            sa.Column('used_at', sa.DateTime(), nullable=True),
            sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
            sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_single_access_tokens_id'), 'single_access_tokens', ['id'], unique=False)
        op.create_index(op.f('ix_single_access_tokens_token'), 'single_access_tokens', ['token'], unique=True)
    
    # Add new columns to users table (check if they exist first)
    user_columns = [col['name'] for col in inspector.get_columns('users')]
    
    if 'whatsapp_phone' not in user_columns:
        op.add_column('users', sa.Column('whatsapp_phone', sa.String(), nullable=True))
        op.create_index(op.f('ix_users_whatsapp_phone'), 'users', ['whatsapp_phone'], unique=True)
    
    if 'registration_complete' not in user_columns:
        op.add_column('users', sa.Column('registration_complete', sa.Boolean(), nullable=True))
        # Set default value for registration_complete for existing users
        op.execute("UPDATE users SET registration_complete = 1 WHERE registration_complete IS NULL")
    
    # Note: SQLite doesn't support ALTER COLUMN, so we skip these for SQLite
    # The model already has these as nullable
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    tables = inspector.get_table_names()
    user_columns = [col['name'] for col in inspector.get_columns('users')]
    
    if 'whatsapp_phone' in user_columns:
        op.drop_index(op.f('ix_users_whatsapp_phone'), table_name='users')
        op.drop_column('users', 'whatsapp_phone')
    
    if 'registration_complete' in user_columns:
        op.drop_column('users', 'registration_complete')
    
    # Drop single_access_tokens table
    if 'single_access_tokens' in tables:
        op.drop_index(op.f('ix_single_access_tokens_token'), table_name='single_access_tokens')
        op.drop_index(op.f('ix_single_access_tokens_id'), table_name='single_access_tokens')
        op.drop_table('single_access_tokens')
    # ### end Alembic commands ###
