"""Add PasswordResetRequest model

Revision ID: f4026b359d0e
Revises: c497361d4ea0
Create Date: 2025-05-31 20:27:53.772638

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f4026b359d0e'
down_revision: Union[str, None] = 'c497361d4ea0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.alter_column('users', 'hashed_password',
    #            existing_type=sa.VARCHAR(),
    #            nullable=False)
    # op.alter_column('users', 'first_name',
    #            existing_type=sa.VARCHAR(),
    #            nullable=False)
    # op.alter_column('users', 'last_name',
    #            existing_type=sa.VARCHAR(),
    #            nullable=False)
    # op.alter_column('users', 'phone',
    #            existing_type=sa.VARCHAR(),
    #            nullable=False)
    # op.alter_column('users', 'email',
    #            existing_type=sa.VARCHAR(),
    #            nullable=False)
    # op.alter_column('users', 'user_type',
    #            existing_type=sa.VARCHAR(),
    #            nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'user_type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'phone',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'last_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'first_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
